### PR TITLE
Use babel's built-in option manager for loading configs

### PR DESCRIPTION
**Pull request by tleunen**
This is a follow up of https://github.com/tleunen/eslint-import-resolver-babel-module/pull/28. Thanks @izaakschroeder for the initial code. I just fixed the default cwd to the project root, using [pkg-up](https://github.com/sindresorhus/pkg-up).

This also means this creates a small breaking change because it forces the paths to be relative to the project root directory (based on `package.json`), but at least we'll be able to support configuration inside presets.

@izaakschroeder would you mind testing the PR?

### CODE REVIEW

**Comment by tleunen** [comment]
It did work well in my case, so I'm merging. This will be part of a v3, since instead of being relative to babelrc file, this must be relative to package.json file by default (this can be modified with the cwd option in babel-plugin-module-resolver).

**Comment by slorber** [comment]
Hi @tleunen 

I got this error that gives a link to this PR, yet I'm not really able to understand the link.

image


I'm trying to lint a RN app with sources in ./src, and have both babel/eslint plugins configured to do so. 
Is there another issue that explains my errors? Where should I use "module:react-native" exactly?

**Comment by tleunen** [comment]
Seems you forgot to include `babel-preset-react-native` in your project?

We have a big `try catch` around babel so we catch other errors unrelated to the plugin unfortunately :s

**Comment by izaakschroeder** [comment]
Yea this error basically means: `babel` encountered some error, we don't really know what to do! We provide the error thrown which you can see at the top there 😄

**Comment by slorber** [comment]
I'm using https://github.com/satya164/eslint-config-satya164 in a RN context and I am able to transpile my project normally, so I normally have all the dependencies needed.

Note in RN, libraries are shipped not transpiled and Metro does transpile node_module libraries too (unlike web where libs tend to be published already transpiled). Can it be the cause? How can we tell this plugin to also babel transpile what is in node modules? because here it seems related to one of my lib

If this plugin have a big try catch, isn't it possible to log the original error that cause the issue? It seems like I don't have the "root cause" of the error here

**Comment by slorber** [comment]
I was wrong apparently this is the root cause.

I'm using https://github.com/expo/expo/tree/master/packages/babel-preset-expo 

I think it's actually because I'm using babel.config.js instead of .babelrc: https://github.com/tleunen/eslint-import-resolver-babel-module/issues/89

**Comment by sdandois** [comment]
> Edit: apparently just adding "babel-preset-react-native" as direct devDependency did solve the issue for me :) not sure why it's not a dep of the expo preset (which extends metro rn preset).

This worked to me too. Apparently, it guess it is not a dep because is already deprecated. I think that you may be using an old module which it is using it in its metro-bundle-config, but it is not a dependency because they guessed that all react-native projects would already have it.

**Pull request merged**
