### PR TITLE
Update plugin key name - improved

### PR DESCRIPTION
**Pull request by fatfisz**
This is a continuation of #75 that contains a compat change for babel-core 7.0.0-beta.3.

### CODE REVIEW

**Comment by fatfisz** [comment]
@tleunen Hi, do you think you'll have time to check it out this week?

**Comment by tleunen** [comment]
Yep definitely. Will do later today. I'm free this weekend :)
But it will be a bit more complicated since we'll probably need to manage both `babel-*` and `@babel/*` packages since v6 uses the first syntax and v7 the new one :/

**Comment by tleunen** [comment]
So I pushed a commit. I removed babel 6 completely and decided to set `@babel/core` as a direct dependency, so we can be sure to use the one we want.

**Comment by fatfisz** [comment]
Shouldn't we preserve compatibility with Babel 6? We could soft-deprecate for now and deprecate completely in the next major version.

I see that the tests are not passing, will look into that after work today.

**Comment by tleunen** [comment]
Because I moved Babel core as a direct dependency, Babel 6 is not really needed anymore.

Yep I noticed it for the tests. I must have used the wrong plugin for the spread operator. Will fix it

**Comment by fatfisz** [comment]
Oops 😛 If the internals are that incompatible, then there's nothing we can do. We can always drop the support in the next major release 🙂

**Comment by tleunen** [comment]
Closing in favor of #78

**Pull request closed without merging**
